language: java
install: skip

os: linux
dist: focal
jdk: oraclejdk17

services:
  - docker
  
jobs:
  include:
    - stage: build
      script: 
        - cd alarm-management
        - chmod +x gradlew
        - ./gradlew build    
    - stage: docker
      script: 
        - cd alarm-management
        - chmod +x gradlew
        - ./gradlew build    
        - docker build -t bla/bla .
