name: Ci Long Night
jobs:
  Frontend - Build:
    steps:
      - type: node-js
        working-directory: alarm-frontend
        shell-script: npm ci
        plugin.docker.imageId: node:lts
      - type: node-js
        working-directory: alarm-frontend
        shell-script: npm run build
        plugin.docker.imageId: node:lts
      - type: gradle
    runs-on: Linux-Medium
    integrations:
      - Docker
    files-publication:
      - alarm-frontend/build/*
  Publish artifacts:
    runs-on: Linux-Medium
    dependencies:
      - Frontend - Build:
          files:
            - alarm-frontend/build/*
    integrations:
      - Docker
    steps:
      - type: script
        script-content: ls -lahR
        working-directory: alarm-frontend/build
  Backend - Build:
    runs-on: Linux-Medium
    steps:
      - type: gradle
        script-content: gradle
        tasks: clean build
        working-directory: alarm-management
        plugin.docker.imageId: gradle:jdk17
        use-gradle-wrapper: 'true'
    files-publication:
      - '**/*'
    parallelism: 2
  Backend - Deploy:
    runs-on: Linux-Medium
    dependencies:
      - Backend - Build:
          files:
            - '**/*'
    steps:
      - type: script
        working-directory: alarm-management/build
        script-content: ls -lahR
parameters:
  Browesr: eqweklqew